#alias aliasname='command'
alias py='python3'
alias mysql-connect='mysql -u root -p'
alias cls='clear'
alias disk-space-usage='wajig large'
alias function-memory-locations='nm'
alias suspend='sudo pm-suspend'
alias ed='emacsclient --no-wait --alternate-editor="" '
alias vim='nvim'
alias data='sudo mount /dev/sdb1 /media/data/'
alias virtualbox='VirtualBox'
