#alias aliasname='command'
alias py='python3'
alias cls='clear'
alias ed='emacsclient -n -a "" -c'
alias vim='nvim'
alias which-port='lsof -i :${port}'
alias share-file='woof'
alias ups='sudo apt update; sudo apt upgrade'
