#alias aliasname='command'
alias py='python3'
alias cls='clear'
alias suspend='sudo pm-suspend'
alias ed='emacsclient --no-wait --alternate-editor="" '
alias vim='nvim'
alias data='sudo mount /dev/sdb1 /media/data/'
